<a href="https://colab.research.google.com/github/charliashby/wrangling/blob/main/Ashby_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
! git clone https://github.com/DS3001/wrangling
%cd wrangling/assignment

fatal: destination path 'wrangling' already exists and is not an empty directory.
/content/wrangling/assignment

In [ ]:
#Question 1

#1. Read the abstract. What is this paper about?
# This paper is about tidy data - data that is easy to manipulate, model, and visualise in the format of: variables as columns, observations as rows, and each type of observational unit is a table.

#2. Read the introduction. What is the "tidy data standard" intended to accomplish?
# Tidy data standard is designed to facilitate initial exploration and analysis of the data, and to simplify the development of data analysis tools that work well together.

#3. Read the intro to section 2. What does this sentence mean: "Like families, tidy datasets are all alike but every messy dataset is messy in its own way." What does this sentence mean: "For a given dataset, itâ€™s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general."
# Messy data sets can be messy in a multitude of ways, whereas tidy datasets can only be tidy in one format.
# We can identify observations and variables by the way it is formatted (rows and columns), but it is more difficult when there is variability across datasets in terms of conceptualization, as well as complex datasets can be nuanced.

#4. Read Section 2.2. How does Wickham define values, variables, and observations?
# Values - numbers (numerical) or strings (categorical)
# Variables - contains all values that measure the same underlying attribute across units
# Observations - contains all values measured on the same unit

#5. How is "Tidy Data" defined in section 2.3?
# Each variable forms a column, each observation forms a row, each type of observational unit forms a table

#6. Read the intro to Section 3 and Section 3.1. What are the 5 most common problems with messy datasets? Why are the data in Table 4 messy? What is "melting" a dataset?
# 5 most common problems are:
# Column headers are values, not variable means
# Multiple variables are stored in one column
# Variables are stored in both rows and columns
# Multiple types of observational units are stored in the same table
# A single observational unit is stored in multiple tables

# Table 4 is messy because variables form both the rows and columns, and column headers are values, not variable names
# Melting a dataset is turning columns into rows

#7. Why, specifically, is table 11 messy but table 12 tidy and "molten"?
# It is not in the format of a tidy dataset: there are values along the top (days).
# Table 12(b) is completely tidy because all the entries are attributes and not variable names.

#8. Read Section 6. What is the "chicken-and-egg" problem with focusing on tidy data? What does Wickham hope happens in the future with further work on the subject of data wrangling?
# if tidy data is only as useful as the tools that work with it, then tidy tools will be inextricably linked to tidy data.
# Wickam hopes others will build on this framework to develop even better data storage strategies and better tools:
# parsing dates and numbers, identifying missing values, correcting character encodings (for international data), matching similar but not identical values (created by typos), verifying experimental design, and filling in structural missing values, not to mention model-based data cleaning that identifies suspicious values, etc.

In [19]:
#Question 2
import pandas as pd
import numpy as np
import seaborn as sns

#1. Numeric variable: For ./data/airbnb_hw.csv, clean the Price variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
df = pd.read_csv('/content/wrangling/assignment/data/airbnb_hw.csv', low_memory=False)
print( df.shape, '\n')
df.head()

price = df['Price']
price = price.str.replace(',','') # Replace commas with nothing
print( price.unique() , '\n')
price = pd.to_numeric(price,errors='coerce') # Typecast price to float/numeric
print( price.unique() , '\n')
print( 'Total missing: ', sum( price.isnull() ) )  # This converts all the values

fatal: destination path 'wrangling' already exists and is not an empty directory.
(30478, 13)

['145' '37' '28' '199' '549' '149' '250' '90' '270' '290' '170' '59' '49'
 '68' '285' '75' '100' '150' '700' '125' '175' '40' '89' '95' '99' '499'
 '120' '79' '110' '180' '143' '230' '350' '135' '85' '60' '70' '55' '44'
 '200' '165' '115' '74' '84' '129' '50' '185' '80' '190' '140' '45' '65'
 '225' '600' '109' '1990' '73' '240' '72' '105' '155' '160' '42' '132'
 '117' '295' '280' '159' '107' '69' '239' '220' '399' '130' '375' '585'
 '275' '139' '260' '35' '133' '300' '289' '179' '98' '195' '29' '27' '39'
 '249' '192' '142' '169' '1000' '131' '138' '113' '122' '329' '101' '475'
 '238' '272' '308' '126' '235' '315' '248' '128' '56' '207' '450' '215'
 '210' '385' '445' '136' '247' '118' '77' '76' '92' '198' '205' '299'
 '222' '245' '104' '153' '349' '114' '320' '292' '226' '420' '500' '325'
 '307' '78' '265' '108' '123' '189' '32' '58' '86' '219' '800' '335' '63'
 '229' '425' '67' '87' '1200' '158' '650' '234' '310' '695' '400' '166'
 '119' '62' '168' '340' '479' '43' '395' '144' '52' '47' '529' '187' '209'
 '233' '82' '269' '163' '172' '305' '156' '550' '435' '137' '124' '48'
 '279' '330' '5000' '134' '378' '97' '277' '64' '193' '147' '186' '264'
 '30' '3000' '112' '94' '379' '57' '415' '236' '410' '214' '88' '66' '71'
 '171' '157' '545' '1500' '83' '96' '1800' '81' '188' '380' '255' '505'
 '54' '33' '174' '93' '740' '640' '1300' '440' '599' '357' '1239' '495'
 '127' '5999' '178' '348' '152' '242' '183' '253' '750' '259' '365' '273'
 '197' '397' '103' '389' '355' '559' '38' '203' '999' '141' '162' '333'
 '698' '46' '360' '895' '10' '41' '206' '281' '449' '388' '212' '102'
 '201' '2750' '4750' '432' '675' '167' '390' '298' '339' '194' '302' '211'
 '595' '191' '53' '361' '480' '8000' '4500' '459' '997' '345' '216' '218'
 '111' '735' '276' '91' '490' '850' '398' '36' '775' '267' '625' '336'
 '2500' '176' '725' '3750' '469' '106' '460' '287' '575' '227' '263' '25'
 '228' '208' '177' '880' '148' '116' '685' '470' '217' '164' '61' '645'
 '699' '405' '252' '319' '268' '419' '343' '525' '311' '840' '154' '294'
 '950' '409' '184' '257' '204' '241' '2000' '412' '121' '288' '196' '900'
 '647' '524' '1750' '309' '510' '1495' '1700' '799' '383' '372' '492'
 '327' '1999' '656' '224' '173' '875' '1170' '795' '690' '146' '465'
 '1100' '151' '274' '429' '825' '282' '256' '1111' '620' '271' '161' '51'
 '855' '579' '1174' '430' '20' '899' '649' '485' '181' '455' '4000' '243'
 '342' '590' '560' '374' '437' '232' '359' '985' '31' '244' '254' '723'
 '237' '428' '370' '34' '1400' '580' '2520' '221' '749' '1600' '2695'
 '306' '202' '680' '570' '520' '223' '2295' '213' '1065' '346' '24' '286'
 '296' '266' '26' '995' '1368' '393' '182' '635' '258' '780' '589' '347'
 '1250' '1350' '446' '3200' '1050' '1650' '1550' '975' '323' '6500' '2499'
 '1850' '2250' '715' '461' '540' '356' '439' '384' '569' '1900' '22' '785'
 '626' '830' '318' '444' '321' '401' '1499' '888' '369' '770' '386' '366'
 '344' '630' '313' '597' '262' '509' '10000' '278' '312' '789' '1195'
 '422' '21' '765' '3500' '945' '326' '3100' '2486' '3390' '1356' '2599'
 '472' '454' '328' '396' '291']

[  145    37    28   199   549   149   250    90   270   290   170    59
    49    68   285    75   100   150   700   125   175    40    89    95
    99   499   120    79   110   180   143   230   350   135    85    60
    70    55    44   200   165   115    74    84   129    50   185    80
   190   140    45    65   225   600   109  1990    73   240    72   105
   155   160    42   132   117   295   280   159   107    69   239   220
   399   130   375   585   275   139   260    35   133   300   289   179
    98   195    29    27    39   249   192   142   169  1000   131   138
   113   122   329   101   475   238   272   308   126   235   315   248
   128    56   207   450   215   210   385   445   136   247   118    77
    76    92   198   205   299   222   245   104   153   349   114   320
   292   226   420   500   325   307    78   265   108   123   189    32
    58    86   219   800   335    63   229   425    67    87  1200   158
   650   234   310   695   400   166   119    62   168   340   479    43
   395   144    52    47   529   187   209   233    82   269   163   172
   305   156   550   435   137   124    48   279   330  5000   134   378
    97   277    64   193   147   186   264    30  3000   112    94   379
    57   415   236   410   214    88    66    71   171   157   545  1500
    83    96  1800    81   188   380   255   505    54    33   174    93
   740   640  1300   440   599   357  1239   495   127  5999   178   348
   152   242   183   253   750   259   365   273   197   397   103   389
   355   559    38   203   999   141   162   333   698    46   360   895
    10    41   206   281   449   388   212   102   201  2750  4750   432
   675   167   390   298   339   194   302   211   595   191    53   361
   480  8000  4500   459   997   345   216   218   111   735   276    91
   490   850   398    36   775   267   625   336  2500   176   725  3750
   469   106   460   287   575   227   263    25   228   208   177   880
   148   116   685   470   217   164    61   645   699   405   252   319
   268   419   343   525   311   840   154   294   950   409   184   257
   204   241  2000   412   121   288   196   900   647   524  1750   309
   510  1495  1700   799   383   372   492   327  1999   656   224   173
   875  1170   795   690   146   465  1100   151   274   429   825   282
   256  1111   620   271   161    51   855   579  1174   430    20   899
   649   485   181   455  4000   243   342   590   560   374   437   232
   359   985    31   244   254   723   237   428   370    34  1400   580
  2520   221   749  1600  2695   306   202   680   570   520   223  2295
   213  1065   346    24   286   296   266    26   995  1368   393   182
   635   258   780   589   347  1250  1350   446  3200  1050  1650  1550
   975   323  6500  2499  1850  2250   715   461   540   356   439   384
   569  1900    22   785   626   830   318   444   321   401  1499   888
   369   770   386   366   344   630   313   597   262   509 10000   278
   312   789  1195   422    21   765  3500   945   326  3100  2486  3390
  1356  2599   472   454   328   396   291]

Total missing:  0

In [20]:
#2. Categorical variable: For the ./data/sharks.csv data covered in the lecture, clean the "Type" variable as well as you can, and explain the choices you make.
df = pd.read_csv('./data/sharks.csv', low_memory=False)
print( df.shape, '\n')
df.head()
df['Type'].value_counts()

type = df['Type'] # Create a temporary vector of values for the Type variable to play with

type = type.replace(['Sea Disaster', 'Boat','Boating','Boatomg'],'Watercraft') # All watercraft/boating values
type.value_counts()

type = type.replace(['Invalid', 'Questionable','Unconfirmed','Unverified','Under investigation'],np.nan) # All unclean values
type.value_counts()

df['Type'] = type # Replace the 'Type' variable with the cleaned version
del type # Destroy the temporary vector

df['Type'].value_counts()

# This is interesting: Sharks are much more likely to kill you if the situation is UNprovoked.
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].replace(['UNKNOWN', 'F','M','2017'],np.nan) # All unclean values
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].replace('y','Y') # All unclean values
pd.crosstab(df['Type'],df['Fatal (Y/N)'],normalize='index')

(6462, 257)

Fatal (Y/N)         N         Y
Type
Provoked     0.967521  0.032479
Unprovoked   0.743871  0.256129
Watercraft   0.684303  0.315697

In [21]:

#3. Dummy variable: For the pretrial data covered in the lecture, clean the WhetherDefendantWasReleasedPretrial variable as well as you can, and, in particular, replace missing values with np.nan.
df = pd.read_parquet('/content/wrangling/data/justice_data.parquet')
print( df.shape, '\n')
df.head()

release = df['WhetherDefendantWasReleasedPretrial']
print(release.unique(),'\n')
print(release.value_counts(),'\n')
release = release.replace(9,np.nan) # In the codebook, the 9's are "unclear"
print(release.value_counts(),'\n')
sum(release.isnull()) # 31 missing values
df['WhetherDefendantWasReleasedPretrial'] = release # Replace data column with cleaned values
del release

(22986, 709)

[9 0 1]

WhetherDefendantWasReleasedPretrial
1    19154
0     3801
9       31
Name: count, dtype: int64

WhetherDefendantWasReleasedPretrial
1.0    19154
0.0     3801
Name: count, dtype: int64

In [22]:
#4. Missing values, not at random: For the pretrial data covered in the lecture, clean the ImposedSentenceAllChargeInContactEvent variable as well as you can, and explain the choices you make. (Hint: Look at the SentenceTypeAllChargesAtConvictionInContactEvent variable.)
length = df['ImposedSentenceAllChargeInContactEvent']
type = df['SentenceTypeAllChargesAtConvictionInContactEvent']

# print( length.unique()  , '\n') # Some values are ' ', denoting missing
length = pd.to_numeric(length,errors='coerce') # Coerce to numeric
length_NA = length.isnull() # Create a missing dummy
print( np.sum(length_NA),'\n') # 9k missing values of 23k, not so good

print( pd.crosstab(length_NA, type), '\n') # Category 4 is cases where the charges were dismissed

length = length.mask( type == 4, 0) # Replace length with 0 when type ==4
length = length.mask( type == 9, np.nan) # Replace length with np.nan when type == 9

length_NA = length.isnull() # Create a new missing dummy
print( pd.crosstab(length_NA, type), '\n')
print( np.sum(length_NA),'\n') # 274 missing, much better

df['ImposedSentenceAllChargeInContactEvent'] = length # Replace data with cleaned version
del length, type # Delete temporary length/type variables

9053

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914     0    0
True                                                 0     0    0  8779  274

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779    0
True                                                 0     0    0     0  274

274